package com.example.orderservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
@DynamoDBTable(tableName = "Orders") // Maps this class to the "Orders" table in DynamoDB
public class Order {

    @DynamoDBHashKey // Marks this field as the primary key (partition key)
    @DynamoDBAutoGeneratedKey // Automatically generates a UUID for the key
    private String orderId;

    @DynamoDBAttribute // Maps this field to an attribute in the DynamoDB table
    private String customerName;

    @DynamoDBAttribute
    private Double orderAmount;

    @DynamoDBAttribute
    private String orderDate; // Stored as an ISO Timestamp string 

    @DynamoDBAttribute
    private String invoiceFileUrl; // The URL to the invoice file in S3 
}